---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/4865/workspace/MavenAnsible-CICD/target/maven-webapp.war"
        dest: "/opt/tomcat/webapps/maven-webapp.war"
        remote_src: no
    - name:  Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
